language: julia

julia:
  - nightly
  - 1.3
  - 1.2

notifications:
  email: false

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.activate("."); Pkg.build(); Pkg.test("Circo"; coverage=false)'
